//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazzetta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazine()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Id { get; set; }
        public string Publication_Name { get; set; }
        public double Publication_Price { get; set; }
        public string Publication_Publisher { get; set; }
        public string Publication_Category { get; set; }
        public string Publication_Language { get; set; }
        public string Publication_Description { get; set; }
        public byte[] Publication_Content { get; set; }
        public int Publication_FileType { get; set; }
        public string Owner_Id { get; set; }
        public byte[] Publication_Thumbnail { get; set; }
        public string Publication_MediaType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
